# Generated by Django 4.2.9 on 2024-01-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image1',
            field=models.ImageField(default=1, upload_to='card/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='image2',
            field=models.ImageField(default=1, upload_to='card/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='image3',
            field=models.ImageField(default=1, upload_to='card/'),
            preserve_default=False,
        ),
    ]
